blank_issues_enabled: true
contact_links:
  - name: ğŸ“œ Docs
    url: https://github.com/shalldie/vscode-background
    about: Please prioritize checking if the answer can be found in README. | è¯·ä¼˜å…ˆæŸ¥çœ‹ README ä¸­æ˜¯å¦å¯ä»¥æ‰¾åˆ°ç­”æ¡ˆã€‚
